### ISSUE TITLE
todo 스타일링 및 기본 틀 잡기

### ISSUE THREAD

**Issue by leedo97y** [leedo97y/mindsai-fe#1]
### Todo

- [x] eslint, prettier 설정
- [x] tsconfig 설정
- [x] todo 컴포넌트 기본 스타일링
- [x] todo editor 컴포넌트 기본 스타일링
- [x] todo list 컴포넌트 기본 스타일링
- [x] page title 수정
- [x] react-icons 패키지 추가
