### ISSUE TITLE
기능 구현

### ISSUE THREAD

**Issue by leedo97y** [leedo97y/mindsai-fe#2]
### Todo

- [x] 삭제 기능 구현
- [x] 수정 기능 구현
- [x] 수정 모드 변경 기능 구현
- [x] todo 체크 박스 구현 (완료)
- [x] 수정 완료 기능 구현
- [x] todo 추가 기능 구현
- [x] 반응형 디자인 추가
